package com.example.kyfar.entity;

public enum Category {
    REAL_ESTATE,
    TRANSPORT,
    TECHNIQUE,
    FASHION_AND_STYLE,
    EVERYTHING_FOR_THE_HOME,
    REPAIR_AND_CONSTRUCTION,
    GARDEN,
    HOBBIES_SPORTS_TOURISM,
    WEDDING_AND_HOLIDAYS,
    ANIMALS,
    WORK_BUSINESS_STUDY,
    SERVICES,
    OTHER

}
